title: Gomix 
enconfig: utf-8
email: guillermo.gomez@gmail.com
description: 
  en: Writing down my legacy
  es: Escribiendo mi legado
index: index.html
exclude: ['tmp','jekyll-multilingual']
highlighter: rouge
paginate: 4
paginate_path: "/posts/page:num/"
excerpt_separator: <!--more-->
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
#  - jekyll-multiple-languages-plugin
#  - 'jekyll-feed'
disqus:
  shortname: Gomix
