title: Gomix 
enconfig: utf-8
email: guillermo.gomez@gmail.com
description: Writing down my legacy
index: index.html
exclude: ['tmp','jekyll-multilingual']
highlighter: rouge
plugins:
  - jekyll-seo-tag
#  - jekyll-multiple-languages-plugin
#  - 'jekyll-feed'
