title: Gomix's Website
#title: 
#  en: Gomix’s website
#  es: Gomix website
enconfig: utf-8
email: guillermo.gomez@gmail.com
description: Writing down my legacy
#description: 
#  en: Writing down my legacy
#  es: Escribiendo mi legado
index: index.html
#index:
#  en: index.html
#  es: indice.html
exclude: ['tmp','jekyll-multilingual']
highlighter: rouge
plugins:
  - "jekyll-seo-tag"
#theme: jekyll-theme-hacker
