theme: jekyll-theme-hacker
title: 
  en: Gomix’s website
  es: Gomix website
email: guillermo.gomez@gmail.com
description: 
  en: Writing down my legacy
  es: Dejando por escrito mi legado
index:
  en: index.html
  es: indice.html
